"use client";
import Header from "@/components/navigation/Header";
import "../globals.css";
import { Inter } from "next/font/google";
import { redirect } from "next/navigation";
import { getCookie } from "cookies-next";
const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const token = getCookie("access-token");
  const resp = await fetch("http://localhost:3000/api/verify", {
    method: "GET",
    headers: {
      Authorization: "Bearer " + token,
    },
    next: { revalidate: 10 },
  });
  if (resp.status === 401) {
    redirect("/login");
  }
  return (
    <>
      <Header />
      <div className="flex-1 px-4 pt-4 flex overflow-y-hidden">{children}</div>
    </>
  );
}
